POST http://localhost:8000/transaction HTTP/1.1
content-type: application/json


{
    "account_no_rsc":3,
    "account_no_des": 2,
    "message": "from 3 to 2 4",
    "amount": 4
}


###
POST http://localhost:8000/transaction/MyTrans HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "limit":-1
}

###
POST http://localhost:8000/transaction/TransSendFrom HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "limit":10
}

###
POST http://localhost:8000/transaction/GetTransDateToDate HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "account_no_des": 3,
    "time_start" :"2022-08-01 20:41:14",
    "time_end" :"2022-08-14 20:41:14",
    "limit":-1
}

###
POST http://localhost:8000/transaction/TransRecieveBy HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "account_no_des": 3,
    "limit":-1
}

###
GET  http://localhost:8000/api/account/2 HTTP/1.1

###

