POST http://localhost:8000/transaction HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "account_no_des": 3,
    "message": "from 2 -> 3",
     "amount": 10
}


###
POST http://localhost:8000/transaction/MyTrans HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "limit":-1
}

###
POST http://localhost:8000/transaction/TransSendFrom HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "limit":-1
}

###
POST http://localhost:8000/transaction/TransRecieveBy HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "limit":-1
}

###
POST http://localhost:8000/transaction/TransRecieveBy HTTP/1.1
content-type: application/json


{
    "account_no_rsc": 2,
    "account_no_des": 3,
    "limit":-1
}

###
GET  http://localhost:8000/api/account/2 HTTP/1.1

###

